services:
  api1: &api
    image: carlsonsantana/rinha-de-backend-2026-java:latest
    environment:
      API_CTRL_SOCK: /run/sockets/api1.ctrl
      INDEX_FILE: /data/index.bin
    volumes:
      - sockets:/run/sockets
    cpuset: "0"
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "160MB"

  api2:
    <<: *api
    environment:
      API_CTRL_SOCK: /run/sockets/api2.ctrl
    cpuset: "1"

  lb:
    image: carlsonsantana/rinha-de-backend-2026-lb:latest
    environment:
      PORT: "9999"
      WORKERS: /run/sockets/api1.ctrl,/run/sockets/api2.ctrl
    ports:
      - "9999:9999"
    volumes:
      - sockets:/run/sockets
    cpuset: "2,3"
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

volumes:
  sockets:
